name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install -D --frozen-lockfile

      - name: Typecheck
        run: bun typecheck

      - name: Lint
        run: bun lint
